 create table Flowers 
 (id integer generated by default as identity, 
 customername varchar(255),
 mobileno varchar(255),
 dateofpurchase varchar(255),
 costofflowers double,
 quantityofflowers int,
 totalamountofflowers double,
  primary key (id));
  
  
 
   <bean id="dataSource"
		class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
		<property name="driverClassName"
			value="org.h2.Driver" />
		<property name="url"
			value="jdbc:h2:tcp://localhost/~/test" />
		<property name="username" value="sa" />
		<property name="password" value="" />
	</bean>
	
<prop key="hibernate.dialect">org.hibernate.dialect.H2Dialect
				</prop>
  
	
	 
  --MySQLDialect
  
	create database flowersdb;

use flowersdb;

 create table Flowers 
 (id integer auto_increment, 
 customername varchar(1500),
 mobileno varchar(1500),
 dateofpurchase varchar(1500),
 costofflowers double,
 quantityofflowers int,
 totalamountofflowers double,
  primary key (id));
	
	
    <bean id="dataSource"
		class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
		<property name="driverClassName"
			value="com.mysql.jdbc.Driver" />
		<property name="url"
			value="jdbc:mysql://localhost:3306/flowersdb" />
		<property name="username" value="root" />
		<property name="password" value="root" />
	</bean> 

org.hibernate.dialect.MySQLDialect
 