 create table Flowers 
 (id integer generated by default as identity, 
 customername varchar(255),
 mobileno varchar(255),
 dateofpurchase varchar(255),
 costofflowers double,
 quantityofflowers int,
 totalamountofflowers double,
  primary key (id));
  
  
 
   <beans:bean id="dataSource"
		class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
		<beans:property name="driverClassName"
			value="org.h2.Driver" />
		<beans:property name="url"
			value="jdbc:h2:tcp://localhost/~/test" />
		<beans:property name="username" value="sa" />
		<beans:property name="password" value="" />
	</beans:bean>
	
	org.hibernate.dialect.H2Dialect
  
	
	 
  --MySQLDialect
  
	create database flowersdb;

use flowersdb;

 create table Flowers 
 (id integer auto_increment, 
 customername varchar(1500),
 mobileno varchar(1500),
 dateofpurchase varchar(1500),
 costofflowers double,
 quantityofflowers int,
 totalamountofflowers double,
  primary key (id));
	
	
  <beans:bean id="dataSource"
	class="org.apache.commons.dbcp.BasicDataSource" destroy-method="close">
	<beans:property name="driverClassName"
			value="com.mysql.jdbc.Driver" />
		<beans:property name="url"
		value="jdbc:mysql://localhost:3306/filedb" />
	<beans:property name="username" value="root" />
	<beans:property name="password" value="root" />
</beans:bean>

org.hibernate.dialect.MySQLDialect
 